quotes/quotesapp/urls.py
from django.urls import path

from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('addtag/', views.addtag, name='addtag'),
    path('addauthor/', views.addauthor, name='addauthor'),
    path('addquote/', views.addqoute, name='addquote'),
    path("author/<str:fullname>", views.author_page, name="author"),
    path("tag/<str:tag>", views.tag_page, name="tag")

]

quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/quotesapp/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f'{self.name}'


class Author(models.Model):
    fullname = models.CharField(max_length=100, unique=True)
    born_date = models.CharField(max_length=150, null=False)
    born_location = models.CharField(max_length=100, null=False)
    description = models.TextField(null=False)

    def __str__(self):
        return f'{self.fullname}'


class Quote(models.Model):
    text = models.TextField(unique=True, null=False)
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.text}: {self.author}, {self.tags}"

    def show_quote_text(self):
        return self.text

    def show_quote_author(self):
        return self.author

    def show_quote_tags(self):
        tag_obj = self.tags.all()
        return tag_obj

quotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField

from .models import Tag, Author, Quote


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=250, widget=TextInput())
    born_date = CharField(widget=TextInput())
    born_location = CharField(widget=TextInput())
    description = CharField(widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):
    text = CharField(max_length=500, required=True, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all())

    class Meta:
        model = Quote
        fields = ['text', 'author']
        exclude = ['tags']

quotes/quotesapp/views.py
from collections import Counter

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

from .forms import TagForm, AuthorForm, QuoteForm
from .models import Tag, Author, Quote


def main(request):
    quotes = Quote.objects.all()
    # populars tags ----------------------->
    all_tags = []
    most_popular_tag = []
    for el in quotes:
        for tag in el.show_quote_tags():
            all_tags.append(tag)
    top_tags = Counter(all_tags).most_common(10)
    for top in top_tags:
        most_popular_tag.append(top[0])
    # paginator --------------------------->
    paginator = Paginator(quotes, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "quotesapp/index.html",
                  context={"quotes": quotes, "most_popular_tag": most_popular_tag, 'page_obj': page_obj})


@login_required
def addtag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/addtag.html', {'form': form})

    return render(request, 'quotesapp/addtag.html', {'form': TagForm()})


@login_required
def addauthor(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/addauthor.html', {'form': form})

    return render(request, 'quotesapp/addauthor.html', {'form': AuthorForm()})


@login_required
def addqoute(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

                return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/addquote.html', {"tags": tags, "authors": authors, 'form': form})

    return render(request, 'quotesapp/addquote.html', {"tags": tags, "authors": authors, 'form': QuoteForm()})


def author_page(request, fullname):
    authors = get_object_or_404(Author, fullname=fullname)

    return render(request, "quotesapp/author.html", {"author": authors})


def tag_page(request, tag):
    tags = get_object_or_404(Tag, name=tag)
    quotes = Quote.objects.all()
    return render(request, "quotesapp/tag.html", {"tag": tags, "quotes": quotes})

quotes/quotesapp/templates/quotesapp/addauthor.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:addauthor' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author full name:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author description:
            {{form.description}}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotesapp/templates/quotesapp/addquote.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:addquote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote text:
            {{ form.text }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>

    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div style="padding: 10px">
        <label> Select Author:
            <select name="author">
                {% for author in authors %}
                <option value="{{author.id}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quotesapp/templates/quotesapp/addtag.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:addtag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotesapp/templates/quotesapp/author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h4>{{ author.fullname }}</h4>
Born {{ author.born_date }} {{ author.born_location }}
<hr>
<h4>About author</h4>
{{ author.description }}

{% endblock %}

quotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
<html lang="en">

<title>Quotes</title>

<head>
    <meta charset="UTF-8"/>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>
<body>

<main class="container">

    {% if user.is_authenticated %}
    <a class="nav-link active" aria-current="page" href="{% url 'users:logout' %}">Logout</a>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/addauthor">Add author</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/addtag">Add tag</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/addquote">Add quote</a>
                    </li>
                </ul>

            </div>
        </div>

        {% else %}
        <a class="enter" href="/users/signup">Sign up</a>
        OR
        <a class="enter" href="/users/login">Login</a>
        {% endif %}
    </nav>

    {% block content %} {% endblock %}

</main>
<footer>
    <center>by Vitalii Zatoka</center>
</footer>
</body>

</html>

quotes/quotesapp/templates/quotesapp/index.html
{% extends "quotesapp/base.html" %}

{% block content %}

<hr>
<h2>Top tags</h2>

{% for el in most_popular_tag %}
<a href="tag/{{ el }}" class="btn btn-primary">|{{ el }}|</a>
{% endfor %}
<hr>

<h2>All quotes</h2>

{% for el in page_obj %}

<div class="card" ,>
    <div class="card-body">
        <strong class="author-name">{{ el.show_quote_author }}</strong>
        <a href="author/{{ el.show_quote_author }}" class="btn btn-primary">More about author</a>
        <p class="card-text">{{ el.show_quote_text }}</p>
        {% for tag in el.show_quote_tags %}
        <a href="tag/{{ tag }}" class="btn btn-primary">|{{ tag }}|</a>
        {% endfor %}
        <hr>
    </div>
</div>
{% endfor %}

<nav>
    <ul>
        {% for p in page_obj.paginator.page_range %}
        {% if page_obj.number == p %}
        <li class="page-num page-num-selected">{{ p }}</li>
        {% else %}
        <li class="page-num">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>

{% endblock %}

quotes/quotesapp/templates/quotesapp/tag.html
{% extends "quotesapp/base.html" %}


{% block content %}

<h4>All quotes for tag {{ tag }} </h4>
<hr>

{% for quote in quotes %}
{% if tag in quote.show_quote_tags %}
<div class="card" ,>
    <div class="card-body">
        <strong class="author-name">{{ quote.show_quote_author }}</strong>
        <a href="/author/{{ quote.show_quote_author }}" class="btn btn-primary">More about author</a>
        <p class="card-text">{{ quote.show_quote_text }}</p>
        {% for tag in quote.show_quote_tags %}
        <a href="/tag/{{ tag }}" class="btn btn-primary">|{{ tag }}|</a>
        {% endfor %}
        <hr>
    </div>
</div>
{% endif %}
{% endfor %}


{% endblock %}